export default {
    normal: [
        require('@/assets/images/bird/bird_img_1.png'),
        require('@/assets/images/bird/bird_img_2.png'),
        require('@/assets/images/bird/bird_img_3.png'),
        require('@/assets/images/bird/bird_img_4.png'),
        require('@/assets/images/bird/bird_img_5.png'),
        require('@/assets/images/bird/bird_img_6.png'),
        require('@/assets/images/bird/bird_img_7.png'),
        require('@/assets/images/bird/bird_img_8.png'),
        require('@/assets/images/bird/bird_img_9.png'),
        require('@/assets/images/bird/bird_img_10.png'),
        require('@/assets/images/bird/bird_img_11.png'),
        require('@/assets/images/bird/bird_img_12.png'),
        require('@/assets/images/bird/bird_img_13.png'),
        require('@/assets/images/bird/bird_img_14.png'),
        require('@/assets/images/bird/bird_img_15.png'),
        require('@/assets/images/bird/bird_img_16.png'),
        require('@/assets/images/bird/bird_img_17.png'),
        require('@/assets/images/bird/bird_img_18.png'),
        require('@/assets/images/bird/bird_img_19.png'),
        require('@/assets/images/bird/bird_img_20.png'),
        require('@/assets/images/bird/bird_img_21.png'),
        require('@/assets/images/bird/bird_img_22.png'),
        require('@/assets/images/bird/bird_img_23.png'),
        require('@/assets/images/bird/bird_img_24.png'),
        require('@/assets/images/bird/bird_img_25.png'),
        require('@/assets/images/bird/bird_img_26.png'),
        require('@/assets/images/bird/bird_img_27.png'),
        require('@/assets/images/bird/bird_img_28.png'),
        require('@/assets/images/bird/bird_img_29.png'),
        require('@/assets/images/bird/bird_img_30.png'),
        require('@/assets/images/bird/bird_img_31.png'),
        require('@/assets/images/bird/bird_img_32.png'),
        require('@/assets/images/bird/bird_img_33.png'),
        require('@/assets/images/bird/bird_img_34.png'),
        require('@/assets/images/bird/bird_img_35.png'),
        require('@/assets/images/bird/bird_img_36.png'),
        require('@/assets/images/bird/bird_img_37.png'),
    ],
    sketch: [
        require('@/assets/images/bird/sketch/bird_img_1.png'),
        require('@/assets/images/bird/sketch/bird_img_2.png'),
        require('@/assets/images/bird/sketch/bird_img_3.png'),
        require('@/assets/images/bird/sketch/bird_img_4.png'),
        require('@/assets/images/bird/sketch/bird_img_5.png'),
        require('@/assets/images/bird/sketch/bird_img_6.png'),
        require('@/assets/images/bird/sketch/bird_img_7.png'),
        require('@/assets/images/bird/sketch/bird_img_8.png'),
        require('@/assets/images/bird/sketch/bird_img_9.png'),
        require('@/assets/images/bird/sketch/bird_img_10.png'),
        require('@/assets/images/bird/sketch/bird_img_11.png'),
        require('@/assets/images/bird/sketch/bird_img_12.png'),
        require('@/assets/images/bird/sketch/bird_img_13.png'),
        require('@/assets/images/bird/sketch/bird_img_14.png'),
        require('@/assets/images/bird/sketch/bird_img_15.png'),
        require('@/assets/images/bird/sketch/bird_img_16.png'),
        require('@/assets/images/bird/sketch/bird_img_17.png'),
        require('@/assets/images/bird/sketch/bird_img_18.png'),
        require('@/assets/images/bird/sketch/bird_img_19.png'),
        require('@/assets/images/bird/sketch/bird_img_20.png'),
        require('@/assets/images/bird/sketch/bird_img_21.png'),
        require('@/assets/images/bird/sketch/bird_img_22.png'),
        require('@/assets/images/bird/sketch/bird_img_23.png'),
        require('@/assets/images/bird/sketch/bird_img_24.png'),
        require('@/assets/images/bird/sketch/bird_img_25.png'),
        require('@/assets/images/bird/sketch/bird_img_26.png'),
        require('@/assets/images/bird/sketch/bird_img_27.png'),
        require('@/assets/images/bird/sketch/bird_img_28.png'),
        require('@/assets/images/bird/sketch/bird_img_29.png'),
        require('@/assets/images/bird/sketch/bird_img_30.png'),
        require('@/assets/images/bird/sketch/bird_img_31.png'),
        require('@/assets/images/bird/sketch/bird_img_32.png'),
        require('@/assets/images/bird/sketch/bird_img_33.png'),
        require('@/assets/images/bird/sketch/bird_img_34.png'),
        require('@/assets/images/bird/sketch/bird_img_35.png'),
        require('@/assets/images/bird/sketch/bird_img_36.png'),
        require('@/assets/images/bird/sketch/bird_img_37.png'),
    ],
    special: {
        jin: {
            normal: require('@/assets/images/bird/bird_img_jin.png'),
            sketch: require('@/assets/images/bird/sketch/bird_img_jin.png'),
        },
        mu: {
            normal: require('@/assets/images/bird/bird_img_mu.png'),
            sketch: require('@/assets/images/bird/sketch/bird_img_mu.png'),
        },
        shui: {
            normal: require('@/assets/images/bird/bird_img_shui.png'),
            sketch: require('@/assets/images/bird/sketch/bird_img_shui.png'),
        },
        huo: {
            normal: require('@/assets/images/bird/bird_img_huo.png'),
            sketch: require('@/assets/images/bird/sketch/bird_img_huo.png'),
        },
        tu: {
            normal: require('@/assets/images/bird/bird_img_tu.png'),
            sketch: require('@/assets/images/bird/sketch/bird_img_tu.png'),
        },
        nan: {
            normal: require('@/assets/images/bird/bird_img_nan.png'),
            sketch: require('@/assets/images/bird/sketch/bird_img_nan.png'),
        },
        nv: {
            normal: require('@/assets/images/bird/bird_img_nv.png'),
            sketch: require('@/assets/images/bird/sketch/bird_img_nv.png'),
        },
        qinglv: {
            normal: require('@/assets/images/bird/bird_img_qinglv.png'),
            sketch: require('@/assets/images/bird/sketch/bird_img_qinglv.png'),
        },
        top: {
            normal: require('@/assets/images/bird/bird_img_top.png'),
            sketch: require('@/assets/images/bird/sketch/bird_img_top.png'),
        },
    }
}